# Generated by Django 6.0.3 on 2026-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=180, unique=True)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de nombre',
                'verbose_name_plural': 'Registros de nombres',
                'ordering': ['full_name'],
            },
        ),
    ]
