# Generated by Django 5.2.5 on 2026-06-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coincidencias', '0002_restructure_namerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(db_index=True, unique=True)),
                ('numero_oficio', models.CharField(blank=True, default='', max_length=80)),
                ('numero_expediente', models.CharField(blank=True, default='', max_length=80)),
                ('solicitud_siara', models.CharField(blank=True, default='', max_length=60)),
                ('anio', models.IntegerField(default=0)),
                ('area_clave', models.CharField(blank=True, default='', max_length=10)),
                ('area_descripcion', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_publicacion', models.DateField()),
                ('dias_plazo', models.IntegerField(default=1)),
                ('autoridad_nombre', models.CharField(blank=True, default='', max_length=220)),
                ('referencia', models.CharField(blank=True, default='', max_length=220)),
                ('referencia1', models.CharField(blank=True, default='', max_length=220)),
                ('tiene_aseguramiento', models.BooleanField(default=False)),
                ('archivo_xml', models.CharField(blank=True, default='', max_length=220)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oficio CNBV',
                'verbose_name_plural': 'Oficios CNBV',
                'ordering': ['-fecha_publicacion', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='PersonaCNBV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField(default=0)),
                ('caracter', models.CharField(blank=True, default='', max_length=60)),
                ('tipo_persona', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=220)),
                ('paterno', models.CharField(blank=True, default='', max_length=80)),
                ('materno', models.CharField(blank=True, default='', max_length=80)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('relacion', models.CharField(blank=True, default='', max_length=120)),
                ('domicilio', models.CharField(blank=True, default='', max_length=320)),
                ('complementarios', models.CharField(blank=True, default='', max_length=220)),
                ('search_full_name', models.CharField(db_index=True, default='', editable=False, max_length=300)),
                ('normalized_name', models.CharField(db_index=True, default='', editable=False, max_length=300)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='coincidencias.oficio')),
            ],
            options={
                'verbose_name': 'Persona CNBV',
                'verbose_name_plural': 'Personas CNBV',
                'ordering': ['oficio', 'persona_id'],
            },
        ),
    ]
